# Generated by Django 5.1.7 on 2025-05-06 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('vegies', 'Vegies'), ('proteins', 'Proteins'), ('carbs', 'Carbs'), ('sauces', 'Sauces'), ('special', 'Special'), ('beverage', 'Beverage')], max_length=20)),
                ('quantity', models.FloatField(default=1)),
                ('unit_of_measurement', models.CharField(choices=[('g', 'grams'), ('kg', 'kilograms'), ('ml', 'milliliters'), ('l', 'liters'), ('tsp', 'teaspoons'), ('tbsp', 'tablespoons'), ('cup', 'cups'), ('piece', 'pieces'), ('slice', 'slices')], default='piece', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MyRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipeName', models.CharField(max_length=100)),
                ('ingredients', models.ManyToManyField(blank=True, to='myApp.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='myApp.myrecipe')),
            ],
            options={
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='Pantry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beverage', models.ManyToManyField(blank=True, related_name='beverage', to='myApp.ingredient')),
                ('carbs', models.ManyToManyField(blank=True, related_name='carbs', to='myApp.ingredient')),
                ('proteins', models.ManyToManyField(blank=True, related_name='proteins', to='myApp.ingredient')),
                ('sauces', models.ManyToManyField(blank=True, related_name='sauces', to='myApp.ingredient')),
                ('special', models.ManyToManyField(blank=True, related_name='special', to='myApp.ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry', to=settings.AUTH_USER_MODEL)),
                ('vegies', models.ManyToManyField(blank=True, related_name='vegies', to='myApp.ingredient')),
            ],
        ),
    ]
