# Generated by Django 5.2.5 on 2025-08-13 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_ingredient_myrecipe_instructionstep_pantry'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_ingredient_per_user'),
        ),
    ]
