# Generated by Django 5.2.5 on 2025-08-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_ingredient_user_alter_ingredient_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myrecipe',
            old_name='recipeName',
            new_name='recipeTitle',
        ),
        migrations.RemoveField(
            model_name='myrecipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='myrecipe',
            name='recipe',
            field=models.TextField(default='No recipe provided'),
        ),
        migrations.DeleteModel(
            name='InstructionStep',
        ),
    ]
